baseURL = 'https://yihaow.com/'
languageCode = 'en-us'
title = 'Yihao Wu'
theme = 'wyh_card_style'

[params]
  profilePhoto = "/images/wyh.jpg"
  name_cn = "吴逸豪"
  name_en = "Yihao Wu"
  position = "PhD Student"
  company = " University of California, Santa Barbara"

